### ISSUE TITLE
Is this actually happening? 

### ISSUE THREAD

**Issue by slarrain** [plotly/dash-demos#1]
Is this the promised Dashboards for Python in Plotly?

If it is, so awesome! It looks great! I SO want to play with this. Congrats and thanks to the Developers. Finally a Shiny for Python!

**Comment by Paul-Yuchao-Dong** [comment]
Share the same HURRAY feeling here!

**Comment by Paul-Yuchao-Dong** [comment]
Is there anyway one can get in the action for Dash?

**Comment by chriddyp** [comment]
Haha thanks @slarrain and @Paul-Yuchao-Dong ! This _is_ really happening, releasing soon. Here's a video with some more info about it: https://www.youtube.com/watch?v=5BAthiN0htc

**Comment by chriddyp** [comment]
@slarrain and @Paul-Yuchao-Dong - Dash is now live! you can check out the docs here: https://plot.ly/dash. I'm going to delete this Repo since we have moved demo apps into separate repos (you can see more demos here: https://plot.ly/dash/gallery). And if you would like to get in touch with me directly: chris@plot.ly :) 

Thanks for your support!
